local chatPage = action_wheel:newPage()
action_wheel:setPage(chatPage)

chatPage:newAction()
    :title("Flüstern")
    :item("minecraft:yellow_dye")
    :onLeftClick(function()
        host:sendChatCommand("flüstern")
    end)

chatPage:newAction()
    :title("Leise")
    :item("minecraft:light_blue_dye")
    :onLeftClick(function()
        host:sendChatCommand("leise")
    end)

chatPage:newAction()
    :title("Reden")
    :item("minecraft:blue_dye")
    :onLeftClick(function()
        host:sendChatCommand("reden")
    end)

chatPage:newAction()
    :title("Rufen")
    :item("minecraft:orange_dye")
    :onLeftClick(function()
        host:sendChatCommand("rufen")
    end)

chatPage:newAction()
    :title("Schreien")
    :item("minecraft:purple_dye")
    :onLeftClick(function()
        host:sendChatCommand("schreien")
    end)

local prevPage

chatPage:newAction()
    :title("Zurück")
    :item("minecraft:barrier")
    :onLeftClick(function ()
        action_wheel:setPage(prevPage)
    end)

return action_wheel:newAction()
    :title("Channle")
    :item("minecraft:goat_horn")
    :onLeftClick(function()
        prevPage = action_wheel:getCurrentPage()
        action_wheel:setPage(chatPage)
    end)
